version: '3'
services:
  web_service:
    container_name: xiusin-web
    build: ./client
    expose:
      - 3000
    ports:
      - ${WEB_PORT}:3000
    volumes:
      - ./client:/web_app
      - /web_app/node_modules
    command: npm run start
    links:
      - api_service
  api_service:
    container_name: xiusin-api
    build: ./server
    expose:
      - ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./server:/api_app
      - /api_app/node_modules
    command: npm run dev
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      API_PORT: ${API_PORT}
      NODE_ENV: development
    links:
      - db_service
  db_service:
    container_name: xiusin-db
    image: postgres:12.0-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - ${POSTGRES_PORT}:5432
volumes:
  db-data:
