version: '3'
services:
  api_service:
    container_name: xiusin-api
    build: ./server
    expose:
      - ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./server/src:/app/src
    command: npm run start
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      API_PORT: ${API_PORT}
    links:
      - db_service
  db_service:
    container_name: xiusin-db
    image: postgres:12.0-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
volumes:
  db-data:
